# Generated by Django 2.1.7 on 2022-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='indextypegoodsbanner',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
    ]
