# Generated by Django 2.1.7 on 2022-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220613_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除标记'),
        ),
    ]
